#!/usr/bin/env ruby

require 'rubygems'
require 'irb/completion'
require 'irb/ext/save-history'

IRB.conf[:AUTO_INDENT] = true
IRB.conf[:EDITOR] = ENV['EDITOR']
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"
IRB.conf[:PROMPT_MODE] = :simple
IRB.conf[:SAVE_HISTORY] = true
IRB.conf[:USE_COLORIZE] = true
