#!/usr/bin/env zsh

# Setting up path
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
PATH="/snap/bin"
PATH="/usr/games:$PATH"
PATH="/usr/local/games:$PATH"
PATH="/sbin:$PATH"
PATH="/usr/sbin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/bin:$PATH"
PATH="/usr/bin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="$HOME/.bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.composer/vendor/bin:$PATH"
PATH="$HOME/.nodenv/shims:$PATH"
PATH="$HOME/.nodenv/bin:$PATH"

if command -v ruby >/dev/null 2>&1; then
    GEM_USER_BIN="$(ruby -r rubygems -e 'print Gem.user_dir' 2>/dev/null)/bin"
    PATH="$GEM_USER_BIN:$PATH"
fi

PATH="$HOME/.rbenv/shims:$PATH"
PATH="$HOME/.rbenv/bin:$PATH"
export PATH

if [[ -n $SSH_TTY ]]; then
    export EDITOR="/usr/bin/vim"
else
    export EDITOR="/usr/bin/codium --wait"
fi

# Setting up PostgreSQL variables
: "${PGHOST:=localhost}"
: "${PGPORT:=5432}"
: "${PGUSER:=developer}"
: "${PGPASSWORD:=developer}"
: "${PGDATABASE:=development}"
export PGHOST PGPORT PGUSER PGPASSWORD PGDATABASE

zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 15

# Setting up variables
export ARCHFLAGS="-arch x86_64"
export CASE_SENSITIVE="false"
export CLICOLOR=1
export COLORTERM="truecolor"
export CSHEDIT="/usr/bin/vim"
export COMPLETION_WAITING_DOTS="true"
export DIRSTACKSIZE=64
export DISABLE_AUTO_TITLE="true"
export DISABLE_LS_COLORS="false"
export DISABLE_MAGIC_FUNCTIONS="false"
export DISABLE_UNTRACKED_FILES_DIRTY="true"
export ENABLE_CORRECTION="true"
export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
export HISTCONTROL="ignoreboth"
export HISTFILE="$HOME/.zsh_history"
export HISTFILESIZE=99999
export HISTSIZE=99999
export HIST_STAMPS="yyyy-mm-dd"
export HYPHEN_INSENSITIVE="false"
export MAILCHECK=60
export LESS_TERMCAP_mb=$'\e[1;31m'      # begin bold
export LESS_TERMCAP_md=$'\e[1;34m'      # begin blink
export LESS_TERMCAP_so=$'\e[01;45;37m'  # begin reverse video
export LESS_TERMCAP_us=$'\e[01;36m'     # begin underline
export LESS_TERMCAP_me=$'\e[0m'         # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'         # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'         # reset underline
export LS_OPTIONS='--color=always'
export MANPAGER="/usr/bin/less -s -M +Gg"
export MANPATH="/usr/local/man:/usr/share/man:$MANPATH"
export MANPATHISSET="yes"
export QUOTING_STYLE="literal"
export PAGER="/usr/bin/most"
export SAVEHIST=99999
export SSH_KEY_PATH="$HOME/.ssh/id_ed25519"
export TEMPDIR="$HOME/.tmp/"
export VISUAL="/usr/bin/vim"
export ZSH_COMPDUMP="$ZSH/cache/.zcompdump-$HOST"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="pygmalion"
