#!/usr/bin/env zsh

# Setting up path
PATH="/snap/bin/"
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
PATH="/usr/games/:$PATH"
PATH="/usr/local/games/:$PATH"
PATH="/sbin/:$PATH"
PATH="/usr/sbin/:$PATH"
PATH="/usr/local/sbin/:$PATH"
PATH="/bin/:$PATH"
PATH="/usr/bin/:$PATH"
PATH="/usr/local/bin/:$PATH"
PATH="/opt/maven/bin:$PATH"
PATH="/opt/java/bin:$PATH"
PATH="$HOME/.bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="$HOME/.local/share/gem/ruby/4.0.0/bin:$PATH"
PATH="$HOME/.composer/vendor/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.nodenv/shims:$PATH"
PATH="$HOME/.nodenv/bin:$PATH"
PATH="$HOME/.rbenv/shims:$PATH"
PATH="$HOME/.rbenv/bin:$PATH"
export PATH

if [[ -n $SSH_TTY ]]; then
    export EDITOR="/usr/bin/vim"
else
    export EDITOR="/usr/bin/codium --wait"
fi

zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 15


# Setting up my favourite theme
ZSH_THEME_GIT_PROMPT_PREFIX="%{${reset_color}%}%F{green}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{${reset_color}%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%F{yellow}⚡%f"
ZSH_THEME_GIT_PROMPT_CLEAN=""

base_prompt="%{${reset_color}%}%F{magenta}%n%F{cyan}@%F{yellow}%m%F{red}:%F{cyan}%0~%F{red}|%f"
post_prompt="%{${reset_color}%}%F{cyan}⇒%f  "
PROMPT="${base_prompt}\$${post_prompt}"
unset base_prompt post_prompt

# Setting up variables
export ARCHFLAGS="-arch x86_64"
export CASE_SENSITIVE="false"
export CLICOLOR=1
export COLORTERM="truecolor"
export CSHEDIT="/usr/bin/vim"
export COMPLETION_WAITING_DOTS="true"
export DIRSTACKSIZE=64
export DISABLE_AUTO_TITLE="true"
export DISABLE_LS_COLORS="false"
export DISABLE_MAGIC_FUNCTIONS="false"
export DISABLE_UNTRACKED_FILES_DIRTY="true"
export EDITOR="/usr/bin/vim"
export ENABLE_CORRECTION="true"
export HISTCONTROL="ignoreboth"
export HISTFILE="$HOME/.zsh_history"
export HISTFILESIZE=99999
export HISTSIZE=99999
export HIST_STAMPS="yyyy-mm-dd"
export HYPHEN_INSENSITIVE="false"
export MAILCHECK=60
export LS_OPTIONS='--color=always'
export MANPATH="/usr/local/man:/usr/share/man:$MANPATH"
export MANPATHISSET="yes"
export QUOTING_STYLE="literal"
export PAGER="/usr/bin/most"
export PROMPT=$PROMPT
export SAVEHIST=99999
export SSH_KEY_PATH="$HOME/.ssh/id_ed25519"
export TEMPDIR="$HOME/.tmp/"
export VISUAL="/usr/bin/vim"
export ZSH_COMPDUMP="$ZSH/cache/.zcompdump-$HOST"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="pygmalion"

export JAVA_HOME="/opt/java"
export MVN_HOME="/opt/maven"
